<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://servicio/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="wsPrueba1" targetNamespace="http://servicio/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://servicio/" elementFormDefault="unqualified" targetNamespace="http://servicio/" version="1.0">

  <xs:element name="echoPrueba" type="tns:echoPrueba"/>

  <xs:element name="echoPruebaResponse" type="tns:echoPruebaResponse"/>

  <xs:complexType name="echoPrueba">
    <xs:sequence>
      <xs:element minOccurs="0" name="cadena" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="echoPruebaResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="echoPruebaResponse">
    <wsdl:part element="tns:echoPruebaResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="echoPrueba">
    <wsdl:part element="tns:echoPrueba" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="wsPrueba1">
    <wsdl:operation name="echoPrueba">
      <wsdl:input message="tns:echoPrueba" name="echoPrueba">
    </wsdl:input>
      <wsdl:output message="tns:echoPruebaResponse" name="echoPruebaResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="wsPrueba1SoapBinding" type="tns:wsPrueba1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="echoPrueba">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="echoPrueba">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="echoPruebaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="wsPrueba1">
    <wsdl:port binding="tns:wsPrueba1SoapBinding" name="wsPrueba1Port">
      <soap:address location="http://localhost:8080/8pm_17oct2018_1/wsPrueba1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>